name: AWS S3 Upload

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: 18

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        env:
          AWS_ACCESS_ID: ${{ env.AWS_ACCESS_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ env.AWS_REGION }}

      - name: Upload to AWS S3
        run: aws s3 sync ../backend/art-images s3://jackc.baylor-jax-art 
        env: 
          AWS_ACCESS_ID: ${{ env.AWS_ACCESS_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}

      - name: Delete images for reload
        run: aws s3 rm ../backend/art-images s3://jackc.balor-jax-art --recursive 
        env: 
          AWS_ACCESS_ID: ${{ env.AWS_ACCESS_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}