name: AWS S3 Upload

on:
  workflow_dispatch:
  push:
    branches: 
      - main 
    paths:
      - frontend/**
  pull_request:
    branches: 
      - main 
    paths:
      - frontend/**

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: 18

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Upload to AWS S3
        working-directory: ./backend
        run: aws s3 sync ../backend/art-images s3://jackc.baylor-jax-art 
        env: 
          AWS_ACCESS_ID: ${{ env.AWS_ACCESS_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}

      - name: Delete images for reload
        working-directory: ./backend
        run: aws s3 rm ../backend/art-images s3://jackc.balor-jax-art --recursive 
        env: 
          AWS_ACCESS_ID: ${{ env.AWS_ACCESS_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}